<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class ActividadAlternativaSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        DB::table('actividades_alternativas')->insert([
            [
                'id_usuario' => 3,
                'titulo' => 'Cosquín Rock',
                'descripcion' => 'Un festival con artistas locales y nacionales.',
                'provincia' => 'Córdoba',
                'localidad' => 'Córdoba Capital',
                'direccion' => 'Av. General Paz 456',
                'horarios' => 'Viernes y sábados de 20:00 a 23:00',
                'costo' => 800,
                'imagen1' => 'cosquin_rock1.jpg',
                'imagen2' => 'cosquin_rock2.jpg',
                'imagen3' => 'cosquin_rock3.jpg',
            ],
            [
                'id_usuario' => 4,
                'titulo' => 'Exposición de Arte',
                'descripcion' => 'Muestra de arte contemporáneo con obras de artistas emergentes.',
                'provincia' => 'Buenos Aires',
                'localidad' => 'Buenos Aires',
                'direccion' => 'Av. de Mayo 789',
                'horarios' => 'De lunes a viernes de 10:00 a 18:00',
                'costo' => 200,
                'imagen1' => 'exposicion_arte1.jpg',
                'imagen2' => 'exposicion_arte2.jpg',
                'imagen3' => 'exposicion_arte3.jpg',
            ],
            [
                'id_usuario' => 4,
                'titulo' => 'Clase de Cocina Regional',
                'descripcion' => 'Aprende a preparar platos tradicionales de la región.',
                'provincia' => 'San Juan',
                'localidad' => 'San Juan Capital',
                'direccion' => 'Calle España 321',
                'horarios' => 'Sábados de 14:00 a 17:00',
                'costo' => 350,
                'imagen1' => 'cocina_regional1.jpg',
                'imagen2' => 'cocina_regional2.jpg',
                'imagen3' => 'cocina_regional3.jpg',
            ],
            [
                'id_usuario' => 4,
                'titulo' => 'Rally en la Montaña',
                'descripcion' => 'Evento deportivo de rally con participación internacional.',
                'provincia' => 'Mendoza',
                'localidad' => 'Mendoza Capital',
                'direccion' => 'Ruta 40 km 1050',
                'horarios' => 'Todo el fin de semana',
                'costo' => 1000,
                'imagen1' => 'rally_montana1.jpg',
                'imagen2' => 'rally_montana2.jpg',
                'imagen3' => 'rally_montana3.jpg',
            ],
            [
                'id_usuario' => 4,
                'titulo' => 'Feria del Libro',
                'descripcion' => 'Encuentro con escritores y venta de libros.',
                'provincia' => 'Santa Fe',
                'localidad' => 'Rosario',
                'direccion' => 'Bv. Oroño 456',
                'horarios' => 'Miércoles a domingo de 11:00 a 20:00',
                'costo' => 150,
                'imagen1' => 'feria_libro1.jpg',
                'imagen2' => 'feria_libro2.jpg',
                'imagen3' => 'feria_libro3.jpg',
            ],
            [
                'id_usuario' => 5,
                'titulo' => 'Mercado de Agricultores',
                'descripcion' => 'Venta de productos orgánicos y frescos de la región.',
                'provincia' => 'La Pampa',
                'localidad' => 'Santa Rosa',
                'direccion' => 'Calle Rivadavia 123',
                'horarios' => 'Sábados de 8:00 a 13:00',
                'costo' => 0,
                'imagen1' => 'mercado_agricultores1.jpg',
                'imagen2' => 'mercado_agricultores2.jpg',
                'imagen3' => 'mercado_agricultores3.jpg',
            ],
            [
                'id_usuario' => 5,
                'titulo' => 'Concierto de Jazz',
                'descripcion' => 'Concierto en vivo con bandas locales de jazz.',
                'provincia' => 'Salta',
                'localidad' => 'Salta Capital',
                'direccion' => 'Calle Urquiza 456',
                'horarios' => 'Viernes de 21:00 a 23:30',
                'costo' => 500,
                'imagen1' => 'concierto_jazz1.jpg',
                'imagen2' => 'concierto_jazz2.jpg',
                'imagen3' => 'concierto_jazz3.jpg',
            ],
            [
                'id_usuario' => 5,
                'titulo' => 'Muestra de Fotografía',
                'descripcion' => 'Exposición de fotografías artísticas y documentales.',
                'provincia' => 'Chaco',
                'localidad' => 'Resistencia',
                'direccion' => 'Calle 9 de Julio 567',
                'horarios' => 'Lunes a viernes de 10:00 a 19:00',
                'costo' => 100,
                'imagen1' => 'muestra_fotografia1.jpg',
                'imagen2' => 'muestra_fotografia2.jpg',
                'imagen3' => 'muestra_fotografia3.jpg',
            ],
            [
                'id_usuario' => 5,
                'titulo' => 'Festejo del Día del Niño',
                'descripcion' => 'Actividades y juegos para los más pequeños.',
                'provincia' => 'Formosa',
                'localidad' => 'Formosa Capital',
                'direccion' => 'Av. 25 de Mayo 789',
                'horarios' => 'Sábado de 10:00 a 16:00',
                'costo' => 0,
                'imagen1' => 'dia_nino1.jpg',
                'imagen2' => 'dia_nino2.jpg',
                'imagen3' => 'dia_nino3.jpg',
            ],
            [
                'id_usuario' => 6,
                'titulo' => 'Torneo de Tenis',
                'descripcion' => 'Competencia de tenis con jugadores locales y visitantes.',
                'provincia' => 'Neuquén',
                'localidad' => 'Neuquén Capital',
                'direccion' => 'Calle Mitre 345',
                'horarios' => 'Todo el fin de semana',
                'costo' => 700,
                'imagen1' => 'torneo_tenis1.jpg',
                'imagen2' => 'torneo_tenis2.jpg',
                'imagen3' => 'torneo_tenis3.jpg',
            ],
            [
                'id_usuario' => 4,
                'titulo' => 'Feria Gastronómica',
                'descripcion' => 'Degustación de comidas típicas de la región.',
                'provincia' => 'Tierra del Fuego',
                'localidad' => 'Ushuaia',
                'direccion' => 'Calle San Martín 654',
                'horarios' => 'Sábados de 11:00 a 20:00',
                'costo' => 200,
                'imagen1' => 'feria_gastronomica1.jpg',
                'imagen2' => 'feria_gastronomica2.jpg',
                'imagen3' => 'feria_gastronomica3.jpg',
            ],
            [
                'id_usuario' => 4,
                'titulo' => 'Armonización Andina',
                'descripcion' => 'Sesiones de yoga y meditación para el bienestar.',
                'provincia' => 'La Rioja',
                'localidad' => 'La Rioja Capital',
                'direccion' => 'Av. 3 de Enero 432',
                'horarios' => 'Domingos de 9:00 a 11:00',
                'costo' => 250,
                'imagen1' => 'jornada_yoga1.jpg',
                'imagen2' => 'jornada_yoga2.jpg',
                'imagen3' => 'jornada_yoga3.jpg',
            ],
            [
                'id_usuario' => 7,
                'titulo' => 'Cine al Aire Libre',
                'descripcion' => 'Proyección de películas en un espacio abierto.',
                'provincia' => 'Chubut',
                'localidad' => 'Trelew',
                'direccion' => 'Calle Belgrano 123',
                'horarios' => 'Sábados a partir de las 20:00',
                'costo' => 150,
                'imagen1' => 'cine_aire_libre1.jpg',
                'imagen2' => 'cine_aire_libre2.jpg',
                'imagen3' => 'cine_aire_libre3.jpg',
            ],
            [
                'id_usuario' => 8,
                'titulo' => 'Taller de Cerámica',
                'descripcion' => 'Aprende técnicas básicas de cerámica y alfarería.',
                'provincia' => 'Jujuy',
                'localidad' => 'San Salvador de Jujuy',
                'direccion' => 'Calle Belgrano 456',
                'horarios' => 'Sábados de 10:00 a 13:00',
                'costo' => 400,
                'imagen1' => 'taller_ceramica1.jpg',
                'imagen2' => 'taller_ceramica2.jpg',
                'imagen3' => 'taller_ceramica3.jpg',
            ],
            [
                'id_usuario' => 4,
                'titulo' => 'Feria del Vino',
                'descripcion' => 'Degustación de vinos locales y nacionales.',
                'provincia' => 'Mendoza',
                'localidad' => 'Mendoza Capital',
                'direccion' => 'Av. San Martín 123',
                'horarios' => 'Viernes a domingos de 14:00 a 22:00',
                'costo' => 500,
                'imagen1' => 'feria_vino1.jpg',
                'imagen2' => 'feria_vino2.jpg',
                'imagen3' => 'feria_vino3.jpg',
            ],
            [
                'id_usuario' => 5,
                'titulo' => 'Maratón Solidaria',
                'descripcion' => 'Evento deportivo para recaudar fondos para organizaciones benéficas.',
                'provincia' => 'Buenos Aires',
                'localidad' => 'Buenos Aires',
                'direccion' => 'Parque Centenario',
                'horarios' => 'Sábado a las 8:00',
                'costo' => 300,
                'imagen1' => 'maraton_solidaria1.jpg',
                'imagen2' => 'maraton_solidaria2.jpg',
                'imagen3' => 'maraton_solidaria3.jpg',
            ],
            [
                'id_usuario' => 3,
                'titulo' => 'Torneo de Fútbol 7',
                'descripcion' => 'Competencia amistosa de fútbol 7 con equipos locales. Ideal para disfrutar de un día de deporte y camaradería.',
                'provincia' => 'Córdoba',
                'localidad' => 'Córdoba Capital',
                'direccion' => 'Complejo Deportivo El Bosque, Av. Valparaíso 123',
                'horarios' => 'Sábados y domingos de 09:00 a 17:00',
                'costo' => 200,
                'imagen1' => 'torneo_futbol1.jpg',
                'imagen2' => 'torneo_futbol2.jpg',
                'imagen3' => 'torneo_futbol3.jpg',
            ],
            [
                'id_usuario' => 4,
                'titulo' => 'Conferencia de Tecnología',
                'descripcion' => 'Charla y paneles sobre las últimas innovaciones tecnológicas.',
                'provincia' => 'Neuquén',
                'localidad' => 'Neuquén Capital',
                'direccion' => 'Av. Argentina 234',
                'horarios' => 'Viernes y sábado de 10:00 a 17:00',
                'costo' => 800,
                'imagen1' => 'conferencia_tecnologia1.jpg',
                'imagen2' => 'conferencia_tecnologia2.jpg',
                'imagen3' => 'conferencia_tecnologia3.jpg',
            ],
            [
                'id_usuario' => 5,
                'titulo' => 'Jornada de Literatura',
                'descripcion' => 'Encuentro con autores y presentaciones de libros.',
                'provincia' => 'Córdoba',
                'localidad' => 'Mina Clavero',
                'direccion' => 'Calle España 789',
                'horarios' => 'Sábados de 10:00 a 14:00',
                'costo' => 200,
                'imagen1' => 'jornada_literatura1.jpg',
                'imagen2' => 'jornada_literatura2.jpg',
                'imagen3' => 'jornada_literatura3.jpg',
            ],
            [
                'id_usuario' => 6,
                'titulo' => 'Feria del Libro',
                'descripcion' => 'Exposición de libros con autores invitados y firmas.',
                'provincia' => 'Salta',
                'localidad' => 'Salta Capital',
                'direccion' => 'Calle 20 de Febrero 456',
                'horarios' => 'Viernes a domingos de 10:00 a 18:00',
                'costo' => 100,
                'imagen1' => 'feria_libro1.jpg',
                'imagen2' => 'feria_libro2.jpg',
                'imagen3' => 'feria_libro3.jpg',
            ],
        ]);
    }
}
