<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class ProvinciaSeeder extends Seeder
{
    /**
     * Corremos el seed de provincias
     */
    public function run(): void
    {
        DB::table('provincias')->insert([
            [
                'id_provincia' => 1,
                'nombre_provincia' => 'Mendoza',
                'imagen_provincia' => 'mendoza.jpg',
                'descripcion_provincia' => 'Mendoza, la "Tierra del Sol y del Buen Vino," es una provincia argentina que cautiva con su espectacular belleza natural y rica tradición vinícola. Rodeada por la majestuosa Cordillera de los Andes, esta región disfruta de un clima soleado y seco, ideal para los amantes del aire libre y el vino. Mendoza es famosa por sus viñedos, especialmente el Malbec, y ofrece una experiencia de degustación incomparable. Además, su legado cultural gauchesco se refleja en festivales, música, danzas y deliciosos platos típicos. Esta provincia combina la emoción de la aventura en la montaña, con el cuidado del medio ambiente y la autenticidad de la cultura argentina, creando un destino turístico excepcional.',
                'ubicacion_provincia' => 'Mendoza se encuentra en la región de Cuyo, en la zona occidental de Argentina. Limita al norte con la provincia de San Juan, al este con San Luis, al sur con La Pampa y al oeste con Chile.',
                'imagen_ubicacion_provincia' => 'mendoza_ubicacion.jpg',
                'cultura_caracteristicas_provincia' => 'Mendoza es un crisol de culturas y tradiciones que se entrelazan en su rica herencia. Los habitantes de Mendoza, conocidos como mendocinos, son famosos por su hospitalidad y calidez. La influencia de la cultura indígena es evidente en la música, la danza y las artesanías de la provincia. Además, la provincia es el hogar de numerosas festividades y celebraciones, incluida la Fiesta Nacional de la Vendimia, que combina la cultura vitivinícola con actuaciones artísticas impresionantes.',
                'flora_fauna_provincia' => 'Mendoza alberga una asombrosa variedad de flora y fauna, adaptadas a su diversidad geográfica que abarca desde el árido desierto en el este hasta las zonas montañosas en el oeste. La región árida del este está salpicada de arbustos resistentes como el jarillal y el piquillín, que han desarrollado adaptaciones únicas para sobrevivir en condiciones de sequía. En contraste, las zonas montañosas y boscosas del oeste albergan una rica diversidad de flora, desde árboles autóctonos como el quebracho colorado hasta una amplia variedad de cactus. En cuanto a la fauna, Mendoza es hogar de especies como el zorro colorado, el guanaco y el puma en las áreas montañosas, mientras que en la zona este se encuentran aves como el hornero y el jote.',
                'historia_provincia' => 'Mendoza tiene una rica historia que abarca desde la época prehispánica hasta la actualidad. La ciudad de Mendoza fue fundada en 1561 por Pedro del Castillo, y la región fue un importante centro económico y cultural durante la época colonial española. Durante el siglo XIX, Mendoza tuvo un papel crucial en la independencia de Argentina. La provincia también es conocida por el devastador terremoto de 1861 que destruyó gran parte de la ciudad de Mendoza, lo que llevó a su reconstrucción. A lo largo de su historia, Mendoza ha sido un centro de actividad agrícola, incluida la viticultura, que ha contribuido significativamente a la economía de Argentina.',
                'region_provincia' => 'Cuyo',
                'created_at' => now(),
                'updated_at' => now(),

            ],
            [
                'id_provincia' => 2,
                'nombre_provincia' => 'Buenos Aires',
                'imagen_provincia' => 'buenos_aires.jpg',
                'descripcion_provincia' => 'Buenos Aires, la provincia más grande y poblada de Argentina, es un crisol de culturas, historia y modernidad. Alberga la vibrante ciudad de Buenos Aires, conocida por su arquitectura europea, vida nocturna, y la pasión por el tango. Fuera de la capital, la provincia ofrece paisajes diversos que van desde las extensas pampas hasta playas atlánticas. La gastronomía porteña es famosa por su carne de res y vinos, haciendo de Buenos Aires un destino esencial para los amantes de la comida y el vino.',
                'ubicacion_provincia' => 'La provincia de Buenos Aires se encuentra en la región central-este de Argentina, limitando al noreste con el Río de la Plata y Uruguay, al este con el océano Atlántico, al sur con La Pampa, al oeste con Córdoba y Santa Fe, y al norte con Entre Ríos.',
                'imagen_ubicacion_provincia' => 'buenos_aires_ubicacion.jpg',
                'cultura_caracteristicas_provincia' => 'La cultura de Buenos Aires es una mezcla vibrante de influencias europeas y latinoamericanas. La ciudad de Buenos Aires, en particular, es famosa por el tango, sus teatros y su vida cultural dinámica. La provincia es también hogar de numerosas festividades, museos y eventos culturales, destacándose por su diversidad artística y cultural.',
                'flora_fauna_provincia' => 'La provincia de Buenos Aires tiene una rica biodiversidad, especialmente en sus zonas rurales y costeras. Las pampas están cubiertas por pastizales que son el hogar de numerosas especies de aves y pequeños mamíferos. En la costa atlántica, se pueden encontrar dunas, playas y bosques que albergan una gran variedad de flora y fauna marina.',
                'historia_provincia' => 'Buenos Aires tiene una historia rica y compleja que se remonta a la época precolombina. La ciudad de Buenos Aires fue fundada en 1536 por Pedro de Mendoza y refundada en 1580 por Juan de Garay. Durante la época colonial, la provincia fue un importante centro comercial y cultural. En el siglo XIX, Buenos Aires jugó un papel crucial en la independencia de Argentina y en la posterior formación del país. La provincia también fue el epicentro de numerosos movimientos políticos y sociales a lo largo de la historia argentina.',
                'region_provincia' => 'Buenos Aires',
                'created_at' => now(),
                'updated_at' => now(),

            ],
            [
                'id_provincia' => 3,
                'nombre_provincia' => 'Neuquén',
                'imagen_provincia' => 'neuquen.jpg',
                'descripcion_provincia' => 'Neuquén es una provincia argentina ubicada en la región de la Patagonia, conocida por sus paisajes impresionantes que incluyen lagos cristalinos, montañas nevadas y bosques densos. Neuquén es un destino popular para el ecoturismo y los deportes al aire libre como el esquí, el senderismo y la pesca. La región también es famosa por sus yacimientos de petróleo y gas, así como por su producción de vino y manzanas.',
                'ubicacion_provincia' => 'Neuquén se encuentra en la región sur de Argentina, limitando al norte con Mendoza, al este con La Pampa y Río Negro, al sur con Río Negro, y al oeste con Chile.',
                'imagen_ubicacion_provincia' => 'neuquen_ubicacion.jpg',
                'cultura_caracteristicas_provincia' => 'La cultura de Neuquén está profundamente influenciada por su herencia patagónica y mapuche. La provincia celebra numerosas festividades que reflejan esta rica mezcla cultural, incluyendo la Fiesta Nacional de la Manzana y el Festival del Chivito. La gastronomía local incluye platos tradicionales como el chivito al asador y empanadas.',
                'flora_fauna_provincia' => 'Neuquén cuenta con una gran diversidad de flora y fauna, adaptadas a su variado paisaje que va desde los Andes hasta las estepas patagónicas. En las zonas montañosas, se encuentran bosques de araucarias y lengas, mientras que las estepas albergan arbustos resistentes y hierbas. Entre la fauna se destacan el huemul, el cóndor andino y diversas especies de peces en sus lagos y ríos.',
                'historia_provincia' => 'La historia de Neuquén está marcada por la presencia de los pueblos originarios mapuche y tehuelche. Durante la colonización española, la región permaneció en gran parte inexplorada hasta la Campaña del Desierto en el siglo XIX. La llegada del ferrocarril a principios del siglo XX y el descubrimiento de petróleo en la década de 1910 transformaron la economía y el desarrollo de la provincia.',
                'region_provincia' => 'Patagonicas',
                'created_at' => now(),
                'updated_at' => now(),

            ],
            [
                'id_provincia' => 4,
                'nombre_provincia' => 'Catamarca',
                'imagen_provincia' => 'catamarca.jpg',
                'descripcion_provincia' => 'Catamarca, ubicada en el noroeste de Argentina, es conocida por sus paisajes montañosos y su rica herencia cultural. La provincia cuenta con una impresionante diversidad de flora y fauna, así como con importantes sitios arqueológicos y una fuerte tradición artesanal. Los turistas pueden disfrutar de actividades como el senderismo, la observación de aves y la exploración de antiguas ruinas.',
                'ubicacion_provincia' => 'Catamarca se encuentra en la región noroeste de Argentina, limitando al norte con Salta, al este con Tucumán y Santiago del Estero, al sur con Córdoba y La Rioja, y al oeste con Chile.',
                'imagen_ubicacion_provincia' => 'catamarca_ubicacion.jpg',
                'cultura_caracteristicas_provincia' => 'La cultura de Catamarca está profundamente influenciada por su historia precolombina y colonial. La provincia celebra numerosas festividades que reflejan esta rica herencia, como la Fiesta Nacional e Internacional del Poncho, que muestra la artesanía local, la música y la danza tradicional.',
                'flora_fauna_provincia' => 'Catamarca alberga una diversidad de ecosistemas, desde los valles fértiles hasta las altas cumbres andinas. Entre la flora se destacan especies como el cardón y la jarilla, mientras que la fauna incluye guanacos, cóndores y flamencos andinos. Las reservas naturales protegen estos hábitats únicos y sus especies endémicas.',
                'historia_provincia' => 'La historia de Catamarca se remonta a la época precolombina, con la presencia de los pueblos diaguitas. Durante la colonización española, la región se convirtió en un importante centro agrícola y minero. La ciudad de San Fernando del Valle de Catamarca fue fundada en 1683. En el siglo XIX, Catamarca jugó un papel activo en las guerras de independencia y en el desarrollo de la nación argentina.',
                'region_provincia' => 'Noroeste',
                'created_at' => now(),
                'updated_at' => now(),

            ],
            [
                'id_provincia' => 5,
                'nombre_provincia' => 'Chaco',
                'imagen_provincia' => 'chaco.jpg',
                'descripcion_provincia' => 'Chaco, ubicada en el noreste de Argentina, es una provincia caracterizada por su biodiversidad y su rica herencia cultural. La provincia cuenta con vastos bosques y humedales, que albergan una gran variedad de flora y fauna. Chaco también es conocido por su artesanía indígena, en particular la producida por las comunidades qom, wichí y moqoit.',
                'ubicacion_provincia' => 'Chaco se encuentra en la región noreste de Argentina, limitando al norte con Formosa, al este con Corrientes, al sur con Santa Fe, y al oeste con Santiago del Estero y Salta.',
                'imagen_ubicacion_provincia' => 'chaco_ubicacion.jpg',
                'cultura_caracteristicas_provincia' => 'La cultura de Chaco está fuertemente influenciada por las comunidades indígenas que habitan la región. La provincia celebra numerosas festividades que reflejan esta diversidad cultural, incluyendo el Festival Nacional del Algodón. La artesanía local, especialmente la cestería y la cerámica, es muy valorada tanto a nivel nacional como internacional.',
                'flora_fauna_provincia' => 'Chaco posee una rica biodiversidad gracias a sus bosques, humedales y pastizales. Entre la flora se destacan especies como el quebracho colorado y el algarrobo. La fauna incluye jaguares, tapires, y una gran variedad de aves y reptiles. Las reservas naturales y los parques nacionales protegen estos ecosistemas únicos.',
                'historia_provincia' => 'La historia de Chaco se remonta a la época precolombina, con la presencia de diversas comunidades indígenas. Durante la colonización española, la región fue explorada pero permaneció en gran parte inexplorada hasta el siglo XIX. En 1951, Chaco fue declarado provincia. Desde entonces, ha experimentado un desarrollo significativo en agricultura, especialmente en el cultivo de algodón.',
                'region_provincia' => 'Nordeste',
                'created_at' => now(),
                'updated_at' => now(),

            ],
            [
                'id_provincia' => 6,
                'nombre_provincia' => 'Corrientes',
                'imagen_provincia' => 'corrientes.jpg',
                'descripcion_provincia' => 'Corrientes, ubicada en el noreste de Argentina, es conocida por sus paisajes acuáticos, su rica historia y su vibrante cultura chamamé. La provincia cuenta con numerosos ríos, arroyos y lagunas, que la convierten en un destino ideal para la pesca y los deportes acuáticos. Corrientes también es famosa por sus carnavales y su patrimonio colonial.',
                'ubicacion_provincia' => 'Corrientes se encuentra en la región noreste de Argentina, limitando al norte con Misiones, al este con Brasil, al sur con Entre Ríos, y al oeste con Chaco y Santa Fe.',
                'imagen_ubicacion_provincia' => 'corrientes_ubicacion.jpg',
                'cultura_caracteristicas_provincia' => 'La cultura de Corrientes está profundamente influenciada por su herencia guaraní y colonial. La provincia es conocida por su música chamamé, un género popular que refleja la mezcla de influencias indígenas y europeas. Corrientes celebra numerosos festivales, incluido el Festival Nacional del Chamamé y los carnavales, que atraen a visitantes de todo el país.',
                'flora_fauna_provincia' => 'Corrientes posee una rica biodiversidad gracias a sus numerosos cuerpos de agua y humedales. Entre la flora se destacan especies como el jacarandá y el ceibo. La fauna incluye yacarés, carpinchos y una gran variedad de aves acuáticas. Las reservas naturales protegen estos ecosistemas únicos y su vida silvestre.',
                'historia_provincia' => 'La historia de Corrientes se remonta a la época precolombina, con la presencia de los pueblos guaraníes. La ciudad de Corrientes fue fundada en 1588 por Juan Torres de Vera y Aragón. Durante la época colonial, la provincia fue un importante centro comercial y militar. En el siglo XIX, Corrientes jugó un papel crucial en las guerras de independencia y en la organización nacional. Hoy en día, es una provincia próspera con una economía basada en la agricultura, la pesca y el turismo.',
                'region_provincia' => 'Nordeste',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_provincia' => 7,
                'nombre_provincia' => 'Entre Ríos',
                'imagen_provincia' => 'entre_rios.jpg',
                'descripcion_provincia' => 'Entre Ríos, ubicada en la región mesopotámica de Argentina, es conocida por sus ríos, arroyos y su exuberante vegetación. La provincia ofrece numerosas oportunidades para el ecoturismo, la pesca y los deportes acuáticos. Entre Ríos también es famosa por sus termas y sus carnavales, que son algunos de los más importantes del país.',
                'ubicacion_provincia' => 'Entre Ríos se encuentra en la región noreste de Argentina, limitando al norte con Corrientes, al este con Uruguay, al sur con Buenos Aires, y al oeste con Santa Fe.',
                'imagen_ubicacion_provincia' => 'entre_rios_ubicacion.jpg',
                'cultura_caracteristicas_provincia' => 'La cultura de Entre Ríos está influenciada por su herencia guaraní y colonial, así como por la inmigración europea. La provincia celebra numerosas festividades que reflejan esta diversidad cultural, incluido el Carnaval de Gualeguaychú, uno de los más grandes y coloridos del país. La música y la danza, especialmente el chamamé y la chamarrita, son parte integral de la vida entrerriana.',
                'flora_fauna_provincia' => 'Entre Ríos posee una gran biodiversidad gracias a sus numerosos cuerpos de agua y humedales. Entre la flora se destacan especies como el ceibo, el jacarandá y el lapacho. La fauna incluye carpinchos, ciervos de los pantanos y una gran variedad de aves acuáticas. Las reservas naturales y los parques nacionales protegen estos ecosistemas únicos.',
                'historia_provincia' => 'La historia de Entre Ríos se remonta a la época precolombina, con la presencia de los pueblos guaraníes. La provincia fue explorada por los españoles en el siglo XVI y se convirtió en un importante centro agrícola y ganadero durante la época colonial. En el siglo XIX, Entre Ríos jugó un papel crucial en las guerras de independencia y en la organización nacional. La ciudad de Paraná fue la capital de la Confederación Argentina entre 1854 y 1861. Hoy en día, Entre Ríos es una provincia próspera con una economía diversificada que incluye la agricultura, la ganadería, el turismo y la industria.',
                'region_provincia' => 'Pampeanas',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_provincia' => 8,
                'nombre_provincia' => 'Formosa',
                'imagen_provincia' => 'formosa.jpg',
                'descripcion_provincia' => 'Formosa, ubicada en el noreste de Argentina, es una provincia conocida por su biodiversidad y sus paisajes naturales, que incluyen humedales, ríos y selvas. La provincia es un destino ideal para el ecoturismo y la observación de fauna silvestre. Formosa también tiene una rica herencia cultural influenciada por las comunidades indígenas y la colonización española.',
                'ubicacion_provincia' => 'Formosa se encuentra en la región noreste de Argentina, limitando al norte con Paraguay, al este con Chaco, al sur con Santa Fe, y al oeste con Salta.',
                'imagen_ubicacion_provincia' => 'formosa_ubicacion.jpg',
                'cultura_caracteristicas_provincia' => 'La cultura de Formosa está influenciada por las comunidades indígenas y la herencia colonial. La provincia celebra numerosas festividades que reflejan esta diversidad cultural, como la Fiesta Nacional del Pomelo. La artesanía local, especialmente la cestería y la cerámica, es muy valorada tanto a nivel nacional como internacional.',
                'flora_fauna_provincia' => 'Formosa posee una rica biodiversidad gracias a sus humedales, ríos y selvas. Entre la flora se destacan especies como el quebracho, el algarrobo y la palma caranday. La fauna incluye yacarés, carpinchos y una gran variedad de aves acuáticas. Las reservas naturales y los parques nacionales protegen estos ecosistemas únicos.',
                'historia_provincia' => 'La historia de Formosa se remonta a la época precolombina, con la presencia de diversas comunidades indígenas. La ciudad de Formosa fue fundada en 1879 por Luis Jorge Fontana. Durante el siglo XX, la provincia se desarrolló gracias a la explotación de sus recursos naturales, incluyendo la agricultura y la ganadería. Formosa también ha jugado un papel importante en la defensa de la soberanía argentina en el noreste.',
                'region_provincia' => 'Nordeste',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_provincia' => 9,
                'nombre_provincia' => 'Jujuy',
                'imagen_provincia' => 'jujuy.jpg',
                'descripcion_provincia' => 'Jujuy, ubicada en el noroeste de Argentina, es conocida por sus impresionantes paisajes montañosos y su rica herencia cultural. La provincia cuenta con una diversidad de ecosistemas, desde las altas cumbres andinas hasta los valles fértiles. Jujuy es famosa por sus tradiciones indígenas, su música folclórica y sus coloridas festividades, como el Carnaval de Humahuaca.',
                'ubicacion_provincia' => 'Jujuy se encuentra en el noroeste de Argentina, limitando al norte con Bolivia, al este con Salta, y al oeste con Chile.',
                'imagen_ubicacion_provincia' => 'jujuy_ubicacion.jpg',
                'cultura_caracteristicas_provincia' => 'La cultura de Jujuy está profundamente influenciada por las comunidades indígenas que habitan la región. La provincia celebra numerosas festividades que reflejan esta rica herencia cultural, incluido el Carnaval de Humahuaca y la Fiesta de la Pachamama. La música y la danza folclórica, así como la artesanía local, son parte integral de la vida jujeña.',
                'flora_fauna_provincia' => 'Jujuy posee una gran diversidad de flora y fauna adaptadas a sus variados ecosistemas. Entre la flora se destacan especies como el cardón y la queñoa. La fauna incluye vicuñas, llamas y cóndores. Las reservas naturales y los parques nacionales protegen estos hábitats únicos y su vida silvestre.',
                'historia_provincia' => 'La historia de Jujuy se remonta a la época precolombina, con la presencia de los pueblos omaguacas y atacamas. La ciudad de San Salvador de Jujuy fue fundada en 1593 por Francisco de Argañaraz y Murguía. Durante la época colonial, la provincia fue un importante centro comercial y militar. En el siglo XIX, Jujuy jugó un papel crucial en las guerras de independencia y en la organización nacional. Hoy en día, es una provincia próspera con una economía basada en la agricultura, la minería y el turismo.',
                'region_provincia' => 'Noroeste',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_provincia' => 10,
                'nombre_provincia' => 'La Pampa',
                'imagen_provincia' => 'la_pampa.jpg',
                'descripcion_provincia' => 'La Pampa, ubicada en el centro de Argentina, es conocida por sus vastas llanuras y su rica herencia agrícola y ganadera. La provincia ofrece un paisaje dominado por la pampa húmeda, ideal para la cría de ganado y la agricultura. La Pampa también cuenta con numerosos parques nacionales y reservas naturales que protegen su biodiversidad y ofrecen oportunidades para el ecoturismo.',
                'ubicacion_provincia' => 'La Pampa se encuentra en el centro de Argentina, limitando al norte con San Luis, Córdoba y Buenos Aires, al este con Buenos Aires, al sur con Río Negro, y al oeste con Mendoza y San Luis.',
                'imagen_ubicacion_provincia' => 'la_pampa_ubicacion.jpg',
                'cultura_caracteristicas_provincia' => 'La cultura de La Pampa está influenciada por su herencia agrícola y ganadera. La provincia celebra numerosas festividades que reflejan esta tradición, como la Fiesta Nacional del Ternero y Día de la Yerra en Ayacucho. La música y la danza folclórica, así como la artesanía local, son parte integral de la vida pampeana.',
                'flora_fauna_provincia' => 'La Pampa posee una gran diversidad de flora y fauna adaptadas a su paisaje de llanuras. Entre la flora se destacan especies como el caldén y el chañar. La fauna incluye guanacos, zorros y una gran variedad de aves. Los parques nacionales y las reservas naturales protegen estos ecosistemas únicos y su vida silvestre.',
                'historia_provincia' => 'La historia de La Pampa se remonta a la época precolombina, con la presencia de los pueblos indígenas mapuches y ranqueles. La provincia fue explorada por los españoles en el siglo XVI y se convirtió en un importante centro agrícola y ganadero durante la época colonial. En el siglo XIX, La Pampa jugó un papel crucial en las guerras de independencia y en la organización nacional. Hoy en día, es una provincia próspera con una economía basada en la agricultura, la ganadería y el turismo.',
                'region_provincia' => 'Pampeanas',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_provincia' => 11,
                'nombre_provincia' => 'La Rioja',
                'imagen_provincia' => 'la_rioja.jpg',
                'descripcion_provincia' => 'La Rioja, ubicada en el noroeste de Argentina, es conocida por sus impresionantes paisajes montañosos y su rica herencia cultural. La provincia cuenta con una diversidad de ecosistemas, desde las altas cumbres andinas hasta los valles fértiles. La Rioja es famosa por sus tradiciones indígenas, su música folclórica y sus coloridas festividades, como el Carnaval de la Chaya.',
                'ubicacion_provincia' => 'La Rioja se encuentra en el noroeste de Argentina, limitando al norte con Catamarca, al este con Córdoba, al sur con San Luis y San Juan, y al oeste con Chile.',
                'imagen_ubicacion_provincia' => 'la_rioja_ubicacion.jpg',
                'cultura_caracteristicas_provincia' => 'La cultura de La Rioja está profundamente influenciada por las comunidades indígenas que habitan la región. La provincia celebra numerosas festividades que reflejan esta rica herencia cultural, incluido el Carnaval de la Chaya y la Fiesta de la Virgen de Andacollo. La música y la danza folclórica, así como la artesanía local, son parte integral de la vida riojana.',
                'flora_fauna_provincia' => 'La Rioja posee una gran diversidad de flora y fauna adaptadas a sus variados ecosistemas. Entre la flora se destacan especies como el cardón y la jarilla. La fauna incluye guanacos, vicuñas y cóndores. Las reservas naturales y los parques nacionales protegen estos hábitats únicos y su vida silvestre.',
                'historia_provincia' => 'La historia de La Rioja se remonta a la época precolombina, con la presencia de los pueblos diaguitas. La ciudad de La Rioja fue fundada en 1591 por Juan Ramírez de Velasco. Durante la época colonial, la provincia fue un importante centro agrícola y minero. En el siglo XIX, La Rioja jugó un papel crucial en las guerras de independencia y en la organización nacional. Hoy en día, es una provincia próspera con una economía basada en la agricultura, la minería y el turismo.',
                'region_provincia' => 'Noroeste',
                'created_at' => now(),
            ],
            [
                'id_provincia' => 12,
                'nombre_provincia' => 'Salta',
                'imagen_provincia' => 'salta.jpg',
                'descripcion_provincia' => 'Salta, ubicada en el noroeste de Argentina, es conocida por sus impresionantes paisajes de montañas, valles y selvas. La provincia es un importante centro de actividades al aire libre, como el senderismo, la escalada y el turismo de aventura. Salta también tiene una rica herencia cultural, influenciada por las comunidades indígenas y la colonización española.',
                'ubicacion_provincia' => 'Salta se encuentra en el noroeste de Argentina, limitando al norte con Bolivia, al este con Formosa y Chaco, al sur con Tucumán y Catamarca, y al oeste con Jujuy y Chile.',
                'imagen_ubicacion_provincia' => 'salta_ubicacion.jpg',
                'cultura_caracteristicas_provincia' => 'La cultura de Salta está profundamente influenciada por las comunidades indígenas y la colonización española. La provincia celebra numerosas festividades que reflejan esta rica herencia cultural, como la Fiesta Nacional de la Vendimia y la Fiesta Nacional del Poncho. La música y la danza folclórica, así como la artesanía local, son parte integral de la vida salteña.',
                'flora_fauna_provincia' => 'Salta posee una gran diversidad de flora y fauna adaptadas a sus variados ecosistemas. Entre la flora se destacan especies como el cardón y la queñoa. La fauna incluye vicuñas, llamas y cóndores. Las reservas naturales y los parques nacionales protegen estos hábitats únicos y su vida silvestre.',
                'historia_provincia' => 'La historia de Salta se remonta a la época precolombina, con la presencia de los pueblos diaguitas y calchaquíes. La ciudad de Salta fue fundada en 1582 por Hernando de Lerma. Durante la época colonial, la provincia fue un importante centro agrícola y minero. En el siglo XIX, Salta jugó un papel crucial en las guerras de independencia y en la organización nacional. Hoy en día, es una provincia próspera con una economía basada en la agricultura, la minería y el turismo.',
                'region_provincia' => 'Noroeste',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_provincia' => 13,
                'nombre_provincia' => 'San Luis',
                'imagen_provincia' => 'san_luis.jpg',
                'descripcion_provincia' => 'San Luis, ubicada en el centro-oeste de Argentina, es conocida por sus hermosos paisajes de sierras, valles y ríos. La provincia ofrece un entorno natural ideal para el ecoturismo, el senderismo y la observación de la fauna. San Luis también cuenta con una rica herencia cultural, reflejada en sus festividades y tradiciones locales.',
                'ubicacion_provincia' => 'San Luis se encuentra en el centro-oeste de Argentina, limitando al norte con La Rioja, al este con Córdoba, al sur con La Pampa, y al oeste con Mendoza y San Juan.',
                'imagen_ubicacion_provincia' => 'san_luis_ubicacion.jpg',
                'cultura_caracteristicas_provincia' => 'La cultura de San Luis está influenciada por su historia colonial y su herencia indígena. La provincia celebra numerosas festividades, como la Fiesta Nacional de la Calle Angosta y la Fiesta de la Dulzura. La música y la danza folclórica, así como la artesanía local, son parte integral de la vida puntana.',
                'flora_fauna_provincia' => 'San Luis posee una diversidad de flora y fauna adaptadas a sus variados ecosistemas, desde las sierras hasta los valles. Entre la flora se destacan especies como el algarrobo y el chañar. La fauna incluye guanacos, zorros y una variedad de aves. Las reservas naturales y los parques nacionales protegen estos hábitats únicos.',
                'historia_provincia' => 'La historia de San Luis se remonta a la época precolombina, con la presencia de los pueblos comechingones y huarpes. La ciudad de San Luis fue fundada en 1594 por Luis Jufré de Loaysa y Meneses. Durante la época colonial, la provincia fue un importante centro agrícola y ganadero. En el siglo XIX, San Luis jugó un papel crucial en las guerras de independencia y en la organización nacional. Hoy en día, es una provincia próspera con una economía basada en la agricultura, la ganadería y el turismo.',
                'region_provincia' => 'Cuyo',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_provincia' => 14,
                'nombre_provincia' => 'Santiago del Estero',
                'imagen_provincia' => 'santiago_del_estero.jpg',
                'descripcion_provincia' => 'Santiago del Estero, ubicada en el norte de Argentina, es conocida por su rica herencia cultural y su historia como una de las ciudades más antiguas del país. La provincia ofrece un entorno caluroso y seco, ideal para la agricultura y la ganadería. Santiago del Estero también cuenta con una vibrante escena cultural, reflejada en sus festividades y tradiciones locales.',
                'ubicacion_provincia' => 'Santiago del Estero se encuentra en el norte de Argentina, limitando al norte con Salta, al este con Chaco y Santa Fe, al sur con Córdoba y Catamarca, y al oeste con Tucumán.',
                'imagen_ubicacion_provincia' => 'santiago_del_estero_ubicacion.jpg',
                'cultura_caracteristicas_provincia' => 'La cultura de Santiago del Estero está profundamente influenciada por su historia y su herencia indígena. La provincia celebra numerosas festividades, como la Fiesta Nacional de la Chacarera y el Festival Nacional de la Salamanca. La música y la danza folclórica, así como la artesanía local, son parte integral de la vida santiagueña.',
                'flora_fauna_provincia' => 'Santiago del Estero posee una diversidad de flora y fauna adaptadas a su clima caluroso y seco. Entre la flora se destacan especies como el quebracho y el algarrobo. La fauna incluye ñandúes, armadillos y una variedad de aves. Las reservas naturales protegen estos hábitats únicos.',
                'historia_provincia' => 'La historia de Santiago del Estero se remonta a la época precolombina, con la presencia de los pueblos tonocotés y sanavirones. La ciudad de Santiago del Estero fue fundada en 1553 por Francisco de Aguirre, siendo la ciudad más antigua de Argentina. Durante la época colonial, la provincia fue un importante centro agrícola y ganadero. En el siglo XIX, Santiago del Estero jugó un papel crucial en las guerras de independencia y en la organización nacional. Hoy en día, es una provincia próspera con una economía basada en la agricultura, la ganadería y el turismo.',
                'region_provincia' => 'Noroeste',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_provincia' => 15,
                'nombre_provincia' => 'Chubut',
                'imagen_provincia' => 'chubut.jpg',
                'descripcion_provincia' => 'Chubut, ubicada en la región patagónica de Argentina, es conocida por sus impresionantes paisajes de montañas, costas y estepas. La provincia es un importante centro de actividades al aire libre, como el avistamiento de ballenas, el senderismo y la pesca. Chubut también tiene una rica herencia cultural, influenciada por las comunidades indígenas y la colonización europea.',
                'ubicacion_provincia' => 'Chubut se encuentra en la región patagónica de Argentina, limitando al norte con Río Negro, al este con el Océano Atlántico, al sur con Santa Cruz, y al oeste con Chile.',
                'imagen_ubicacion_provincia' => 'chubut_ubicacion.jpg',
                'cultura_caracteristicas_provincia' => 'La cultura de Chubut está influenciada por las comunidades indígenas y la colonización europea, especialmente por los inmigrantes galeses. La provincia celebra numerosas festividades, como el Eisteddfod del Chubut y la Fiesta Nacional del Asado. La música y la danza folclórica, así como la artesanía local, son parte integral de la vida chubutense.',
                'flora_fauna_provincia' => 'Chubut posee una gran diversidad de flora y fauna adaptadas a sus variados ecosistemas. Entre la flora se destacan especies como el coirón y el calafate. La fauna incluye ballenas, pingüinos y guanacos. Las reservas naturales y los parques nacionales protegen estos hábitats únicos y su vida silvestre.',
                'historia_provincia' => 'La historia de Chubut se remonta a la época precolombina, con la presencia de los pueblos tehuelches. La región fue explorada por los españoles en el siglo XVI y se integró a la República Argentina en el siglo XIX. Durante el siglo XIX y XX, Chubut experimentó un notable crecimiento económico gracias a la inmigración galesa y a la explotación de sus recursos naturales, incluyendo la pesca y la ganadería. Hoy en día, es una provincia próspera con una economía diversificada que incluye la agricultura, la industria y el turismo.',
                'region_provincia' => 'Patagonicas',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_provincia' => 16,
                'nombre_provincia' => 'Santa Cruz',
                'imagen_provincia' => 'santa_cruz.jpg',
                'descripcion_provincia' => 'Santa Cruz, ubicada en la región patagónica de Argentina, es conocida por sus impresionantes paisajes de glaciares, montañas y costas. La provincia es un importante centro de actividades al aire libre, como el trekking, la pesca y el avistamiento de fauna marina. Santa Cruz también tiene una rica herencia cultural, influenciada por las comunidades indígenas y la colonización europea.',
                'ubicacion_provincia' => 'Santa Cruz se encuentra en la región patagónica de Argentina, limitando al norte con Chubut, al este con el Océano Atlántico, al sur y al oeste con Chile.',
                'imagen_ubicacion_provincia' => 'santa_cruz_ubicacion.jpg',
                'cultura_caracteristicas_provincia' => 'La cultura de Santa Cruz está influenciada por las comunidades indígenas y la colonización europea. La provincia celebra numerosas festividades, como la Fiesta Nacional del Lago Argentino y la Fiesta Nacional del Róbalo. La música y la danza folclórica, así como la artesanía local, son parte integral de la vida santacruceña.',
                'flora_fauna_provincia' => 'Santa Cruz posee una gran diversidad de flora y fauna adaptadas a sus variados ecosistemas. Entre la flora se destacan especies como el ñire y el coihue. La fauna incluye guanacos, pumas y cóndores. Las reservas naturales y los parques nacionales protegen estos hábitats únicos y su vida silvestre.',
                'historia_provincia' => 'La historia de Santa Cruz se remonta a la época precolombina, con la presencia de los pueblos tehuelches y aonikenk. La región fue explorada por los españoles en el siglo XVI y se integró a la República Argentina en el siglo XIX. Durante el siglo XIX y XX, Santa Cruz experimentó un notable crecimiento económico gracias a la explotación de sus recursos naturales, incluyendo la minería y la ganadería. Hoy en día, es una provincia próspera con una economía diversificada que incluye la agricultura, la industria y el turismo.',
                'region_provincia' => 'Patagonicas',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_provincia' => 17,
                'nombre_provincia' => 'Misiones',
                'imagen_provincia' => 'misiones.jpg',
                'descripcion_provincia' => 'Misiones, ubicada en el noreste de Argentina, es conocida por sus espectaculares paisajes naturales, incluyendo las famosas Cataratas del Iguazú. La provincia cuenta con una gran diversidad biológica, protegida en parte por el Parque Nacional Iguazú. Misiones también tiene una rica herencia cultural influenciada por las comunidades guaraníes y la colonización europea.',
                'ubicacion_provincia' => 'Misiones se encuentra en el noreste de Argentina, limitando al norte con Paraguay y Brasil, al este con Brasil, al sur con Corrientes y al oeste con Paraguay.',
                'imagen_ubicacion_provincia' => 'misiones_ubicacion.jpg',
                'cultura_caracteristicas_provincia' => 'La cultura de Misiones está profundamente influenciada por las comunidades guaraníes y la colonización europea. La provincia celebra numerosas festividades que reflejan esta diversidad cultural, incluido el Festival Nacional del Inmigrante. La artesanía local, especialmente la cestería y la talla en madera, es muy valorada tanto a nivel nacional como internacional.',
                'flora_fauna_provincia' => 'Misiones posee una rica biodiversidad gracias a sus selvas tropicales y subtropicales. Entre la flora se destacan especies como el lapacho, el palo rosa y la yerba mate. La fauna incluye jaguares, tapires y una gran variedad de aves. Las reservas naturales y los parques nacionales protegen estos ecosistemas únicos.',
                'historia_provincia' => 'La historia de Misiones se remonta a la época precolombina, con la presencia de las comunidades guaraníes. La región fue explorada por los españoles en el siglo XVI y se convirtió en un importante centro de las misiones jesuíticas durante la época colonial. En el siglo XIX, Misiones se integró a la República Argentina y comenzó un proceso de colonización europea. Hoy en día, es una provincia próspera con una economía basada en la agricultura, el turismo y la industria.',
                'region_provincia' => 'Nordeste',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_provincia' => 18,
                'nombre_provincia' => 'Córdoba',
                'imagen_provincia' => 'cordoba.jpg',
                'descripcion_provincia' => 'Córdoba, ubicada en el centro de Argentina, es conocida por sus paisajes serranos, su vibrante vida cultural y su importante legado histórico. La provincia es un destacado centro turístico, educativo y económico, con una mezcla única de tradiciones coloniales y modernas. Córdoba también se distingue por su rica herencia cultural, reflejada en sus festividades, música y gastronomía.',
                'ubicacion_provincia' => 'Córdoba se encuentra en el centro de Argentina, limitando al norte con Catamarca y Santiago del Estero, al este con Santa Fe, al sur con Buenos Aires y La Pampa, y al oeste con San Luis y La Rioja.',
                'imagen_ubicacion_provincia' => 'cordoba_ubicacion.jpg',
                'cultura_caracteristicas_provincia' => 'La cultura de Córdoba está profundamente influenciada por su historia colonial y su herencia indígena. La provincia celebra numerosas festividades, como el Festival Nacional de Doma y Folklore en Jesús María y el Carnaval de Villa General Belgrano. La música y la danza folclórica, así como la gastronomía local, son parte integral de la vida cordobesa.',
                'flora_fauna_provincia' => 'Córdoba posee una gran diversidad de flora y fauna adaptadas a sus variados ecosistemas, desde las sierras hasta los valles y llanuras. Entre la flora se destacan especies como el quebracho y el algarrobo. La fauna incluye pumas, zorros y una variedad de aves. Las reservas naturales y los parques nacionales protegen estos hábitats únicos.',
                'historia_provincia' => 'La historia de Córdoba se remonta a la época precolombina, con la presencia de los pueblos comechingones y sanavirones. La ciudad de Córdoba fue fundada en 1573 por Jerónimo Luis de Cabrera. Durante la época colonial, la provincia fue un importante centro educativo y religioso, gracias a la presencia de la Universidad Nacional de Córdoba, fundada en 1613. En el siglo XIX, Córdoba jugó un papel crucial en las guerras de independencia y en la organización nacional. Hoy en día, es una provincia próspera con una economía diversificada que incluye la industria, la agricultura, el turismo y la educación.',
                'region_provincia' => 'Pampeanas',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_provincia' => 19,
                'nombre_provincia' => 'Santa Fe',
                'imagen_provincia' => 'santa_fe.jpg',
                'descripcion_provincia' => 'Santa Fe, ubicada en el centro-este de Argentina, es conocida por sus fértiles tierras agrícolas, su vibrante vida cultural y su importante legado histórico. La provincia es un destacado centro económico y educativo, con una mezcla única de tradiciones coloniales y modernas. Santa Fe también se distingue por su rica herencia cultural, reflejada en sus festividades, música y gastronomía.',
                'ubicacion_provincia' => 'Santa Fe se encuentra en el centro-este de Argentina, limitando al norte con Chaco, al este con Corrientes y Entre Ríos, al sur con Buenos Aires, y al oeste con Córdoba y Santiago del Estero.',
                'imagen_ubicacion_provincia' => 'santa_fe_ubicacion.jpg',
                'cultura_caracteristicas_provincia' => 'La cultura de Santa Fe está profundamente influenciada por su historia colonial y su herencia indígena. La provincia celebra numerosas festividades, como el Festival Nacional de Folklore en Cosquín y el Carnaval de Santa Fe. La música y la danza folclórica, así como la gastronomía local, son parte integral de la vida santafesina.',
                'flora_fauna_provincia' => 'Santa Fe posee una gran diversidad de flora y fauna adaptadas a sus variados ecosistemas, desde las llanuras hasta los humedales. Entre la flora se destacan especies como el quebracho y el algarrobo. La fauna incluye pumas, carpinchos y una variedad de aves acuáticas. Las reservas naturales y los parques nacionales protegen estos hábitats únicos.',
                'historia_provincia' => 'La historia de Santa Fe se remonta a la época precolombina, con la presencia de los pueblos guaraníes y chanás. La ciudad de Santa Fe fue fundada en 1573 por Juan de Garay. Durante la época colonial, la provincia fue un importante centro agrícola y ganadero. En el siglo XIX, Santa Fe jugó un papel crucial en las guerras de independencia y en la organización nacional. Hoy en día, es una provincia próspera con una economía diversificada que incluye la agricultura, la industria, el turismo y la educación.',
                'region_provincia' => 'Pampeanas',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_provincia' => 20,
                'nombre_provincia' => 'Río Negro',
                'imagen_provincia' => 'rio_negro.jpg',
                'descripcion_provincia' => 'Río Negro, ubicada en la Patagonia argentina, es conocida por su diversidad geográfica que incluye desde la costa atlántica hasta los Andes. La provincia ofrece una mezcla de paisajes impresionantes, desde la estepa patagónica hasta exuberantes bosques y lagos cristalinos. Bariloche, uno de sus destinos más famosos, es ideal para actividades al aire libre como el esquí, senderismo y pesca. Además, Río Negro es reconocida por su producción de frutas, especialmente manzanas y peras, en el Valle del Río Negro.',
                'ubicacion_provincia' => 'Río Negro se encuentra en la región patagónica de Argentina. Limita al norte con la provincia de La Pampa, al este con Buenos Aires, al sur con Chubut y al oeste con Neuquén y Chile.',
                'imagen_ubicacion_provincia' => 'rio_negro_ubicacion.jpg',
                'cultura_caracteristicas_provincia' => 'Río Negro es una provincia con una rica herencia cultural que incluye la influencia de los pueblos originarios mapuches y tehuelches, así como la cultura europea traída por los inmigrantes. Las fiestas populares, la música folclórica y las danzas tradicionales son parte integral de la vida en Río Negro. La Fiesta Nacional de la Manzana es una de las celebraciones más importantes de la provincia, destacando la producción frutícola de la región.',
                'flora_fauna_provincia' => 'Río Negro cuenta con una flora y fauna diversa, adaptada a sus diferentes ecosistemas. En la región andina, se encuentran especies como el ciprés de la cordillera y el coihue, mientras que en la estepa patagónica predominan los arbustos bajos y resistentes como el coirón. La fauna incluye especies como el guanaco, el puma y el cóndor andino en las zonas montañosas, y una variedad de aves acuáticas y mamíferos marinos en la costa atlántica.',
                'historia_provincia' => 'Río Negro tiene una historia rica y variada, con evidencias de asentamientos humanos que datan de miles de años. La provincia fue explorada por primera vez por los europeos en el siglo XVI. A lo largo de los siglos, la región ha sido testigo de numerosos conflictos y acuerdos entre los pueblos indígenas y los colonizadores. En el siglo XIX, Río Negro se incorporó oficialmente a la República Argentina y desde entonces ha experimentado un crecimiento significativo, especialmente en términos de desarrollo agrícola y turístico.',
                'region_provincia' => 'Patagonicas',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_provincia' => 21,
                'nombre_provincia' => 'San Juan',
                'imagen_provincia' => 'san_juan.jpg',
                'descripcion_provincia' => 'San Juan es una provincia ubicada en la región de Cuyo, conocida por su clima árido y su producción vitivinícola. La provincia se destaca por su paisaje montañoso y desértico, con impresionantes formaciones geológicas y reservas naturales. San Juan es famosa por sus vinos, especialmente el Syrah, y ofrece rutas del vino que permiten a los visitantes conocer bodegas y viñedos de la región. También es conocida por el Parque Provincial Ischigualasto, o Valle de la Luna, un sitio de interés paleontológico y turístico.',
                'ubicacion_provincia' => 'San Juan se encuentra en la región de Cuyo, en la zona centro-oeste de Argentina. Limita al norte con La Rioja, al este con San Luis, al sur con Mendoza y al oeste con Chile.',
                'imagen_ubicacion_provincia' => 'san_juan_ubicacion.jpg',
                'cultura_caracteristicas_provincia' => 'San Juan tiene una rica herencia cultural influenciada por los pueblos indígenas y la colonización española. La provincia es conocida por sus festividades religiosas y culturales, incluyendo la Fiesta Nacional del Sol, que celebra la historia y la cultura sanjuanina con desfiles, espectáculos y actividades recreativas. La música y la danza folclórica, así como la artesanía local, son elementos destacados de la cultura de San Juan.',
                'flora_fauna_provincia' => 'La flora de San Juan incluye una variedad de especies adaptadas al clima árido, como los algarrobos, jarillas y chañares. La fauna es igualmente diversa, con animales como el puma, el guanaco y la vizcacha en las áreas más desérticas y montañosas. En las reservas naturales y parques provinciales, se pueden observar aves como el cóndor andino y el águila mora.',
                'historia_provincia' => 'La historia de San Juan se remonta a la época prehispánica, con la presencia de los pueblos indígenas huarpes. La ciudad de San Juan fue fundada en 1562 por Juan Jufré y ha sido un importante centro agrícola y vitivinícola desde entonces. Durante el siglo XIX, San Juan jugó un papel crucial en la independencia de Argentina. La provincia también es conocida por el terremoto de 1944 que destruyó gran parte de la ciudad de San Juan, lo que llevó a su reconstrucción y modernización. A lo largo de su historia, San Juan ha sido un importante productor de vinos y otros productos agrícolas.',
                'region_provincia' => 'Cuyo',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_provincia' => 22,
                'nombre_provincia' => 'Tierra del Fuego, Antártida e Islas del Atlántico Sur',
                'imagen_provincia' => 'tierra_del_fuego.jpg',
                'descripcion_provincia' => 'Tierra del Fuego, Antártida e Islas del Atlántico Sur es la provincia más austral de Argentina, conocida por su impresionante paisaje de montañas, glaciares y bosques subantárticos. Ushuaia, la ciudad más austral del mundo, es el principal centro urbano y turístico de la provincia. Tierra del Fuego ofrece una variedad de actividades al aire libre, incluyendo trekking, navegación por el Canal Beagle y visitas al Parque Nacional Tierra del Fuego. La provincia también es un punto de partida para expediciones a la Antártida.',
                'ubicacion_provincia' => 'Tierra del Fuego se encuentra en el extremo sur de Argentina, compartiendo la isla principal con Chile. Limita al norte con el Estrecho de Magallanes, al este con el Océano Atlántico, al sur con el Canal Beagle y al oeste con Chile.',
                'imagen_ubicacion_provincia' => 'tierra_del_fuego_ubicacion.jpg',
                'cultura_caracteristicas_provincia' => 'La cultura de Tierra del Fuego está influenciada por los pueblos originarios yámanas y selknam, así como por los inmigrantes europeos que se asentaron en la región. La provincia celebra diversas festividades, incluyendo el Festival Internacional de Ushuaia, que presenta una amplia variedad de música clásica y contemporánea. La artesanía local, las leyendas fueguinas y la gastronomía basada en productos del mar son elementos importantes de la cultura fueguina.',
                'flora_fauna_provincia' => 'Tierra del Fuego posee una rica biodiversidad que incluye especies adaptadas a su clima frío y húmedo. Los bosques subantárticos están dominados por lengas y guindos, mientras que la fauna incluye animales como el guanaco, el zorro colorado fueguino y el cóndor andino. En las zonas costeras, se pueden encontrar colonias de pingüinos, lobos marinos y una variedad de aves marinas.',
                'historia_provincia' => 'La historia de Tierra del Fuego está marcada por la presencia de los pueblos indígenas yámanas y selknam, quienes habitaron la región durante miles de años. En el siglo XIX, la región fue explorada por navegantes europeos y posteriormente colonizada por Argentina y Chile. Ushuaia fue fundada en 1884 y se convirtió en un importante centro administrativo y penal. A lo largo del siglo XX, la provincia se desarrolló gracias a la industria pesquera, la exploración de petróleo y el turismo. Tierra del Fuego es conocida hoy en día como un destino turístico de renombre internacional y una puerta de entrada a la Antártida.',
                'region_provincia' => 'Patagonicas',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_provincia' => 23,
                'nombre_provincia' => 'Tucumán',
                'imagen_provincia' => 'tucuman.jpg',
                'descripcion_provincia' => 'Tucumán, conocida como el "Jardín de la República", es la provincia más pequeña de Argentina en términos de superficie, pero rica en historia y cultura. Es famosa por su paisaje verde y montañoso, con parques nacionales y reservas naturales que ofrecen un refugio para la biodiversidad. San Miguel de Tucumán, la capital, es un importante centro histórico donde se firmó la declaración de independencia de Argentina en 1816. Tucumán también es conocida por su producción de azúcar y limones.',
                'ubicacion_provincia' => 'Tucumán se encuentra en la región del noroeste argentino. Limita al norte con Salta, al este con Santiago del Estero y al sur y oeste con Catamarca.',
                'imagen_ubicacion_provincia' => 'tucuman_ubicacion.jpg',
                'cultura_caracteristicas_provincia' => 'Tucumán tiene una rica herencia cultural influenciada por los pueblos indígenas y la colonización española. La provincia celebra numerosas festividades, incluyendo la Fiesta Nacional de la Empanada y la Fiesta de la Caña de Azúcar. La música folclórica, las danzas tradicionales y la gastronomía, especialmente las empanadas tucumanas, son elementos destacados de la cultura de Tucumán.',
                'flora_fauna_provincia' => 'La flora de Tucumán incluye una diversidad de especies adaptadas a su clima subtropical y montañoso, con bosques de yungas que albergan árboles como el cedro, el laurel y el nogal. La fauna es igualmente diversa, con animales como el tapir, el pecarí y el ocelote en las áreas boscosas, así como una variedad de aves, incluyendo el tucán y el loro barranquero.',
                'historia_provincia' => 'Tucumán tiene una rica historia que se remonta a la época prehispánica con la presencia de los pueblos indígenas diaguitas y calchaquíes. La ciudad de San Miguel de Tucumán fue fundada en 1565 por Diego de Villarroel y se convirtió en un importante centro económico y cultural durante la época colonial. En 1816, Tucumán fue el escenario de la declaración de independencia de Argentina. La provincia también es conocida por su producción agrícola, especialmente de azúcar y limones, que ha sido una parte importante de su economía desde el siglo XIX.',
                'region_provincia' => 'Noroeste',
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ]);
    }
}
